allowBuilds:
  bedrock-native-math: true
  better-sqlite3: true
overrides:
  prismarine-chunk: "github:GenerelSchwerz/prismarine-chunk#bedrock-1.26-compat"
  bedrock-native-math: "github:mc-zuri/bedrock-native-math"
  minecraft-data: "github:mc-zuri/node-minecraft-data#bedrock-v2"
